"""Focus area definitions — labels, NewsAPI queries, and article-matching signals."""

from __future__ import annotations

FOCUS_AREA_KEYS: tuple[str, ...] = (
    "macro",
    "stock-markets",
    "central-banks-rates",
    "commodities-energy",
    "technology-ai",
    "real-estate-housing",
    "crypto-digital-assets",
    "geopolitics-trade",
    "uk-politics-economy",
    "us-politics-economy",
    "sport",
    "manufacturing-industry",
    "consumer-retail",
    "healthcare-pharma",
)

FOCUS_AREA_LABELS: dict[str, str] = {
    "macro": "Macro Economics",
    "stock-markets": "Stock Markets",
    "central-banks-rates": "Central Banks & Rates",
    "commodities-energy": "Commodities & Energy",
    "technology-ai": "Technology & AI",
    "real-estate-housing": "Real Estate & Housing",
    "crypto-digital-assets": "Crypto & Digital Assets",
    "geopolitics-trade": "Geopolitics & Trade",
    "uk-politics-economy": "UK Politics & Economy",
    "us-politics-economy": "US Politics & Economy",
    "sport": "Sport & Business",
    "manufacturing-industry": "Manufacturing & Industry",
    "consumer-retail": "Consumer & Retail",
    "healthcare-pharma": "Healthcare & Pharma",
}

FOCUS_AREA_HINTS: dict[str, str] = {
    "macro": "Focuses on broad economic trends, growth, and global market context.",
    "stock-markets": "Focuses on equity indices, share prices, and market moves.",
    "central-banks-rates": "Focuses on central banks, interest rates, and monetary policy.",
    "commodities-energy": "Focuses on oil, gas, metals, renewables, and commodity markets.",
    "technology-ai": "Focuses on technology companies, AI, semiconductors, and software.",
    "real-estate-housing": "Focuses on property markets, mortgages, and housing policy.",
    "crypto-digital-assets": "Focuses on bitcoin, crypto markets, and digital assets.",
    "geopolitics-trade": "Focuses on geopolitical risk, trade policy, and sanctions.",
    "uk-politics-economy": "Focuses on Westminster, UK policy, and the British economy.",
    "us-politics-economy": "Focuses on Washington, US policy, and the American economy.",
    "sport": "Focuses on sports business, media rights, and major events.",
    "manufacturing-industry": "Focuses on factories, industrial output, and supply chains.",
    "consumer-retail": "Focuses on retail sales, brands, and consumer spending.",
    "healthcare-pharma": "Focuses on pharma, biotech, healthcare policy, and drug approvals.",
}

LEGACY_FOCUS_AREA_ALIASES: dict[str, str] = {
    "uk-politics": "uk-politics-economy",
    "tech": "technology-ai",
    "energy": "commodities-energy",
}

GENERAL_NEWS_CATEGORY_QUERIES: dict[str, str] = {
    "macro": '"inflation" OR "interest rates" OR "central bank" OR "bond yields" OR "jobs report" OR "global economy"',
    "stock-markets": '"stock market" OR "S&P 500" OR "FTSE 100" OR "Nasdaq" OR "equities" OR "share prices"',
    "central-banks-rates": '"central bank" OR "interest rates" OR "Federal Reserve" OR "Bank of England" OR "bond yields" OR "monetary policy"',
    "commodities-energy": '"oil prices" OR "OPEC" OR "natural gas" OR "renewables" OR "gold price" OR "commodities"',
    "technology-ai": '"artificial intelligence" OR "AI" OR "semiconductors" OR "cloud computing" OR "cybersecurity" OR "software" OR "technology"',
    "real-estate-housing": '"real estate" OR "housing market" OR "mortgage rates" OR "property prices" OR "home sales" OR "rent"',
    "crypto-digital-assets": '"bitcoin" OR "cryptocurrency" OR "ethereum" OR "digital assets" OR "crypto market"',
    "geopolitics-trade": '"geopolitics" OR "trade war" OR "sanctions" OR "tariffs" OR "supply chain" OR "international trade" OR "diplomatic"',
    "uk-politics-economy": '"UK politics" OR "Westminster" OR "Downing Street" OR "Parliament" OR "UK government" OR "UK economy" OR "UK budget"',
    "us-politics-economy": '"US politics" OR "White House" OR "Congress" OR "Senate" OR "US government" OR "US economy" OR "Federal budget"',
    "sport": '"Premier League" OR "Champions League" OR "World Cup" OR "Olympics" OR "Wimbledon" OR "Formula 1" OR "NBA" OR "NFL" OR "cricket" OR "tennis"',
    "manufacturing-industry": '"manufacturing" OR "industrial production" OR "factory orders" OR "PMI" OR "industrial sector" OR "supply chain"',
    "consumer-retail": '"retail" OR "consumer spending" OR "e-commerce" OR "supermarket" OR "high street" OR "shopping"',
    "healthcare-pharma": '"pharmaceutical" OR "biotech" OR "FDA" OR "healthcare" OR "drug approval" OR "NHS" OR "clinical trial"',
}

CATEGORY_SIGNALS: dict[str, tuple[str, ...]] = {
    "macro": (
        "gdp",
        "inflation",
        "cpi",
        "ppi",
        "economic growth",
        "recession",
        "fiscal policy",
        "monetary policy",
        "central bank",
        "interest rates",
        "deficit",
        "trade balance",
        "manufacturing",
        "employment",
        "jobs report",
        "economy",
        "economic",
    ),
    "stock-markets": (
        "stocks",
        "shares",
        "markets",
        "wall street",
        "s&p 500",
        "s&p",
        "dow",
        "nasdaq",
        "ftse",
        "dax",
        "index",
        "indices",
        "bull market",
        "bear market",
        "volatility",
        "rally",
        "sell-off",
        "sell off",
        "market cap",
        "ipo",
        "listing",
        "stock market",
        "equities",
        "share price",
    ),
    "central-banks-rates": (
        "fed",
        "federal reserve",
        "bank of england",
        "ecb",
        "interest rate",
        "interest rates",
        "rate hike",
        "rate cut",
        "quantitative easing",
        " qe ",
        "bond yield",
        "yields",
        "monetary policy",
        "inflation target",
        "central bank",
        "basis points",
    ),
    "commodities-energy": (
        "commodity",
        "commodities",
        "energy",
        "oil",
        "gas",
        "opec",
        "brent",
        "crude",
        "natural gas",
        "lng",
        "renewable",
        "renewables",
        "solar",
        "wind power",
        "nuclear",
        "gold price",
        "copper",
        "wheat",
        "refinery",
    ),
    "technology-ai": (
        "technology",
        "tech ",
        "artificial intelligence",
        " ai ",
        "machine learning",
        "semiconductor",
        "chip",
        "chips",
        "cloud",
        "software",
        "cybersecurity",
        "data centre",
        "data center",
        "nvidia",
        "startup",
    ),
    "real-estate-housing": (
        "real estate",
        "property market",
        "housing market",
        "home prices",
        "house prices",
        "mortgage",
        "mortgages",
        "rental",
        "landlord",
        "commercial property",
        "reit",
        "housing starts",
        "building permits",
    ),
    "crypto-digital-assets": (
        "bitcoin",
        "ethereum",
        "cryptocurrency",
        "crypto",
        "blockchain",
        "digital asset",
        "digital assets",
        "stablecoin",
        "defi",
        "crypto exchange",
        "btc",
    ),
    "geopolitics-trade": (
        "geopolit",
        "trade war",
        "tariff",
        "tariffs",
        "sanction",
        "sanctions",
        "supply chain",
        "export",
        "imports",
        "diplomatic",
        "conflict",
        "nato",
        "middle east",
        "ukraine",
        "taiwan",
    ),
    "uk-politics-economy": (
        "uk politics",
        "westminster",
        "downing street",
        "parliament",
        "chancellor",
        "uk economy",
        "british economy",
        "bank of england",
        "budget",
        "labour party",
        "conservative party",
        "general election",
        "brexit",
        "uk gdp",
    ),
    "us-politics-economy": (
        "us politics",
        "white house",
        "congress",
        "senate",
        "republican",
        "democrat",
        "us economy",
        "american economy",
        "federal budget",
        "infrastructure bill",
        "supreme court",
        "presidential",
    ),
    "sport": (
        "sport",
        "sports",
        "football",
        "soccer",
        "tennis",
        "cricket",
        "rugby",
        "golf",
        "match",
        "league",
        "cup final",
        "formula 1",
        "f1",
        "nba",
        "nfl",
        "mlb",
        "olympics",
        "world cup",
        "champions league",
        "wimbledon",
        "sports rights",
        "media rights",
        "stadium",
        "franchise",
        "franchise valuation",
        "athlete earnings",
        "sponsorship deal",
        "sports investment",
        "league valuation",
        "sports betting",
        "team acquisition",
        "sport business",
        "premier league",
    ),
    "manufacturing-industry": (
        "manufacturing",
        "factory",
        "factories",
        "industrial",
        "industry",
        "production line",
        "pmi",
        "industrial output",
        "supply chain",
        "automation",
        "machinery",
        "aerospace",
        "automotive",
    ),
    "consumer-retail": (
        "retail",
        "retailer",
        "consumer",
        "consumer spending",
        "shopping",
        "e-commerce",
        "supermarket",
        "high street",
        "brand sales",
        "footfall",
        "luxury goods",
        "fast-moving consumer",
    ),
    "healthcare-pharma": (
        "healthcare",
        "health care",
        "pharma",
        "pharmaceutical",
        "biotech",
        "drug",
        "fda",
        "clinical trial",
        "hospital",
        "nhs",
        "vaccine",
        "medical",
        "life sciences",
    ),
}

# Legacy API / saved-profile keys → same queries and signals as current areas.
for _legacy, _target in LEGACY_FOCUS_AREA_ALIASES.items():
    if _target in GENERAL_NEWS_CATEGORY_QUERIES:
        GENERAL_NEWS_CATEGORY_QUERIES.setdefault(_legacy, GENERAL_NEWS_CATEGORY_QUERIES[_target])
    if _target in CATEGORY_SIGNALS:
        CATEGORY_SIGNALS.setdefault(_legacy, CATEGORY_SIGNALS[_target])
    if _target in FOCUS_AREA_LABELS:
        FOCUS_AREA_LABELS.setdefault(_legacy, FOCUS_AREA_LABELS[_target])


def normalize_focus_area_key(key: str) -> str:
    k = (key or "macro").strip().lower()
    k = LEGACY_FOCUS_AREA_ALIASES.get(k, k)
    if k in FOCUS_AREA_LABELS:
        return k
    return "macro"


def focus_area_label(key: str) -> str:
    k = normalize_focus_area_key(key)
    return FOCUS_AREA_LABELS.get(k, FOCUS_AREA_LABELS["macro"])


def focus_area_hint(key: str) -> str:
    k = normalize_focus_area_key(key)
    return FOCUS_AREA_HINTS.get(k, FOCUS_AREA_HINTS["macro"])
